name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js with pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      # Step 3: Install pnpm
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      # Step 4: Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 5: Build the Next.js app
      - name: Build Next.js app
        run: pnpm build

      # Step 6: Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.5Be3Tyk679D0JHvZG4BpOZhJ }}
          vercel-args: '--prod'
          working-directory: .
